version: '2'
services:
    dns:
        restart: always
        image: axxyhtrx/dnsmasq
        volumes:
            - ./dnsmasq.conf:/etc/dnsmasq.conf
            - ./xmpp.hosts:/etc/xmpp.hosts
        ports:
            - "53:53/udp"
        cap_add:
            - NET_ADMIN
